autocmd Filetype gitcommit setlocal spell textwidth=72
autocmd BufNewFile,BufRead Vagrantfile set filetype=ruby

" Don’t reset cursor to start of line when moving around.
set nostartofline

set number                     " Show current line number
set relativenumber             " Show relative line numbers
