# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder
# Configuration
# --------------------------------------
source $HOME/dev/dotfiles/zsh/config/options.zsh
source $HOME/dev/dotfiles/zsh/config/variables.zsh
source $HOME/dev/dotfiles/zsh/config/aliases.zsh
source $HOME/dev/dotfiles/zsh/config/suggestions.zsh
ZSH_TMUX_AUTOSTART=true
ZSH_TMUX_ITERM2=true

plugins=(git docker docker-compose zsh-completions zsh-syntax-highlighting asdf zsh-history-substring-search)
source /opt/homebrew/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
autoload -Uz compinit && compinit
function exists { which $1 &> /dev/null }
export PATH="$PATH:/Applications/Visual Studio Code.app/Contents/Resources/app/bin"
export PATH="/opt/homebrew/opt/libpq/bin:$PATH"
export DOTNET_ROOT=/usr/local/share/dotnet
export PATH=$PATH:$HOME/dotnet
export PGGSSENCMODE="disable"
. /opt/homebrew/opt/asdf/libexec/asdf.sh
export PATH="$HOME/.bin:$PATH"
export GOPATH="$HOME/go"
export PATH="$GOPATH/bin:$PATH"
eval "$(/opt/homebrew/bin/brew shellenv)"

export BUNDLER_EDITOR="code"
eval "$(starship init zsh)"
source <(fzf --zsh)
source $(brew --prefix)/share/zsh-history-substring-search/zsh-history-substring-search.zsh


# export NVM_DIR="$HOME/.nvm"
# [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
# [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
