# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder
# Configuration
# --------------------------------------
source $HOME/dev/dotfiles/zsh/config/options.zsh
source $HOME/dev/dotfiles/zsh/config/variables.zsh
source $HOME/dev/dotfiles/zsh/config/aliases.zsh
source $HOME/dev/dotfiles/zsh/config/suggestions.zsh
ZSH_TMUX_AUTOSTART=true
ZSH_TMUX_ITERM2=true
# Which plugins would you like to load?
# Standard plugins can be found in $ZSH/plugins/
# Custom plugins may be added to $ZSH_CUSTOM/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git docker docker-compose zsh-completions zsh-syntax-highlighting asdf)
if type brew &>/dev/null; then
  FPATH=$(brew --prefix)/share/zsh-completions:$FPATH

  autoload -Uz compinit
  compinit
fi
source /opt/homebrew/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
# export PATH="/opt/homebrew/opt/postgresql@15/bin:$PATH"
# export PATH="/Users/gabriel.desilets/Library/Python/3.9/bin:$PATH"
# export PATH="$PATH:/Applications/Visual Studio Code.app/Contents/Resources/app/bin"
# export DOTNET_ROOT=$HOME/dotnet
# export PATH=$PATH:$HOME/dotnet
export PGGSSENCMODE="disable"
. /opt/homebrew/opt/asdf/libexec/asdf.sh
eval "$(starship init zsh)"


export PATH="$HOME/.bin:$PATH"
